### ISSUE TITLE
Example eslint v9 config 

### ISSUE THREAD

**Issue by LucasHillDex** [intlify/eslint-plugin-svelte#17]
Would it be possible to provide a config that will work with the new flat config format in eslint v9?

I see that support was added in this PR: https://github.com/intlify/eslint-plugin-svelte/pull/12

However, when I look at the code I don't see an exported config that is compatible with v9. All the exported configs use the old "extends" format https://github.com/intlify/eslint-plugin-svelte/blob/main/lib/configs/recommended.ts. I could totally be missing it though. 

Thanks!

**Comment by LucasHillDex** [comment]
I was able to get this working by using the eslint compat helper..

```
import { fixupPluginRules } from '@eslint/compat';
import intlifySvelte from '@intlify/eslint-plugin-svelte';

const intlifyFixedPlugin = fixupPluginRules(intlifySvelte);

export default [
  {
    plugins: {
      '@intlify/svelte': intlifyFixedPlugin
    },
    rules: {
      '@intlify/svelte/no-raw-text': 'error'
    },
    ignores: ['**/*.test.svelte']
  },

```

But a native flat config format would be great!

**Comment by ota-meshi** [comment]
Oh, the plugin doesn't provide flat config yet.
Could you please consider opening a PR if possible?

**Comment by codiini** [comment]
Hey @ota-meshi I'd like to pick this up

**Comment by ota-meshi** [comment]
@codiini  Thank you! I'm looking forward to your pull request!
